extends:
    - prettier
overrides:
    - files: "*.ts"
      extends:
        - prettier
        - "plugin:@typescript-eslint/recommended"
        - "plugin:@typescript-eslint/recommended"
parserOptions:
    ecmaVersion: 8